site_name: Learning Graph RAG
site_description: 'Resources for learning Graph RAG'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/graph-rag/'
repo_url: 'https://github.com/dmccreary/graph-rag'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Graph RAG Concepts:
    - Introduction: concepts/index.md
    - Entity Extraction: concepts/entity-extraction.md
    - Concept Extraction: concepts/concept-extraction.md
    - Concept Networks: concepts/concept-networks.md
    - Wordnet: concepts/wordnet.md
    - Graph Algorithms: concepts/graph-algorithms.md
    - Prompts: concepts/prompts.md
    - Ollama: concepts/ollama.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX